feat: "создал контроллеры и тесты"
jamshut007/java-filmorate pull request #1
Opened 2022-06-08 13:34 UTC by jamshut007

2022-06-09 21:46 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private int count = 0;
для генерации айдишников нужно сделать отдельный сервис, который будет сюда добавлен как поле

2022-06-09 21:48 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final LocalDate movieBirthday = LocalDate.of(1895, 12, 28);
это поле не меняется, можно сделать константой `private static final LocalDate EARLEST_RELEASE_DATE`

2022-06-09 21:50 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("{}", film);
в текст лога стоит добавить сообщение перед фильмом `log.info("Фильм создан: {}", film)`
а то при значении null будет выведено странное сообщение

2022-06-09 21:51 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private boolean checkFilm(Film film) {
метод лучше назвать `isFilmNameUnique`

2022-06-09 21:53 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private void checkException(Film film) throws ValidationException {
метод лучше назвать `validateFilm`, 
а ValidationException сделать наследником RuntimeException, тогда исключение не придется обрабатывать или декларировать в сигнатуре метода

2022-06-09 21:53 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +public class UserController {
нужно исправить такие же замечания, как в FilmController

2022-06-09 21:55 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new ValidationException("продолжительность фильма должна быть положительной.");
лучше изменить сообщение на `"Продолжительность фильма должна быть больше 0, текущая - " + film.duration`

2022-06-09 21:56 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            throw new ValidationException("логин не может быть пустым и содержать пробелы.");
в сообщения стоит добавлять значения, которые оказались невалидными, чтобы легче понимать, в чем ошибка

2022-06-09 21:58 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/exception/ValidationException.java
> +        log.warn(s);
если исключение будет создано, но не брошено, то лог все равно выведется

можно выводить лог перед тем, как выбросить исключение

2022-06-09 21:59 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +@Builder
аннотации легче читать, когда они в порядке увеличения длины выставлены

2022-06-09 22:02 UTC, makholin commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +    public static String USER_NOT_CREATE = "пользователь не создался";
сообщения ассертов и сообщения в логах в константы выносить не нужно, потому что они редко повторяются в нескольких местах и их лучше видеть сразу в коде, чем переходить к объявлению константы

2022-06-09 22:02 UTC, makholin requested changes
Нужно исправить замечания

2022-06-10 07:47 UTC, jamshut007 commented on src/main/java/ru/yandex/practicum/filmorate/exception/ValidationException.java
> +        log.warn(s);
Вот здесь не понял куда лог нужно перенести. в методах validateUser и validateFilm в каждую конструкцию if?
тогда вместо одного прописанного лога в классе ValidationException будет прописано 8 логов?

2022-06-10 08:10 UTC, closed without merging