feat: "Создал сервисы, хранилища. В сервисе появилась бизнес логика"
jamshut007/java-filmorate pull request #3
Opened 2022-06-18 08:30 UTC by jamshut007

2022-06-18 21:15 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    public Map<String, String> handleValidationException(final ValidationException e) {
Лучше возвращать какой-то свой класс Error, чем мапу

тем более в мапе странно организовано хранение: ключ - сообщение об ошибке, и значение - сообщение об ошибке из исключения

2022-06-18 21:16 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    @ExceptionHandler
можно сделать одну аннотацию на весь класс

2022-06-18 21:19 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (!filmService.getFilmStorage().getFilms().containsKey(id)) {
контроллеры ничего не должны знать о сторадже: у сервиса не должно быть метода, который возвращает сторадж

у сервиса должен быть метод `getFilms` или `exits(int filmId)`, который вызывает внутри нужные методы у стораджа

2022-06-18 21:20 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new NullPointerException("Фильм отсутствует с id: " + id);
нужно свое исключение NotFoundException, которое будет преобразовываться в ответ HTTP 404

2022-06-18 21:23 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            count = "10";
10 стоит вынести в константу и сделать тип int

и в этом методе делать так:
`int filmCount = count != null ? Integer.parseInt(count) : DEFAULT_FILMS_COUNT;`

2022-06-18 21:24 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new NullPointerException("Фильм с названием " +
тоже должно быть подходящее исключение для такой ситуации

2022-06-18 21:26 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +@Data
такой аннотации не должно быть у сервисных классов
она подходит только для классов, которые представляют какую-то модель данных

2022-06-18 21:28 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        Set<Integer> friendsId = getUserStorage().getUser(id).getFriends();
название должно быть `friendIds`, потому что тут можественное число айдишников, а не друзей

2022-06-18 21:29 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            Set<Integer> man = new HashSet<>(getUserStorage().getUser(id).getFriends());
название `man` у какого-то множества интов ничего не говорит о том, что хранится в этом сете
с `otherMan` такая же ситуация

2022-06-18 21:30 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    private IdGenerator generator = new IdGenerator();
`IdGeneator` тоже нужно сделать спринговым компонентов и добавлять его в зависимости через injection

2022-06-18 21:32 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        if (film.getId() == 0) {
0 стоит сделать константой, потому что это значение показывает, что ид не создан

но лучше для id таким значением сделать например -1, так будет более понятно

2022-06-18 21:33 UTC, makholin requested changes
Нужно убрать аннотации Data с сервисных классов и сделать свои исключения для бизнес ошибок (наследовать их лучше от RuntimeException)

И другие замечания нужно исправить

2022-06-19 12:21 UTC, jamshut007 commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    public Map<String, String> handleValidationException(final ValidationException e) {
В практикуме при изучении обработки ошибок был предложен вариант с мапой, поменял ErrorResponse, но разницу не почувствовал.

2022-06-21 07:16 UTC, merged