Add database
jamshut007/java-filmorate pull request #6
Opened 2022-07-17 11:00 UTC by jamshut007

2022-07-18 15:47 UTC, makholin commented
В commit message лучше писать осмысленный текст:
пример как пишут в спринге https://github.com/spring-projects/spring-framework/commits/main

2022-07-18 15:49 UTC, makholin commented on .mvn/wrapper/maven-wrapper.properties
> +spring.datasource.url=jdbc:postgresql://localhost:5432/cats
эти настройки должны быть в файле application.yaml

2022-07-18 15:52 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    FilmService service;
должен быть private final

название нужно filmService, потому что потом в контроллере может быть много сервисов

2022-07-18 15:54 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +    GenreService service;
private final

2022-07-18 15:55 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private List<Genre> genres;
можно сразу инициализировать пустым списком, чтобы не получить npe при доступе к элементам

2022-07-18 15:56 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +    public Genre(int id, String name) {
@AllArgrConstructor может заменить этот код

2022-07-18 16:15 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    static Film makeFilm(ResultSet rs, int rowNum) throws SQLException {
нужно сделать нестатичным приватным и убрать 2й аргумент: он не используется

2022-07-18 16:15 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    private List<Genre> getGenresByIdUser(long id) {
приватные методы принято делать после всех публичных

2022-07-18 16:17 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +
достаточно одной пустой строки

2022-07-18 16:20 UTC, makholin requested changes
Нужно исправить замечания
многие замечания относятся не к одному месту, а к нескольким  местам

2022-07-19 17:40 UTC, makholin commented on .mvn/wrapper/maven-wrapper.properties
> +lass-name=org.postgresql.Driver
должно быть `class`?

2022-07-19 17:42 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +
достаточно одной пустой строки

2022-07-19 17:44 UTC, makholin approved these changes
Работа принята

2022-07-19 17:47 UTC, jamshut007 commented on .mvn/wrapper/maven-wrapper.properties
> +lass-name=org.postgresql.Driver
плохо удалилось) сейчас до удалю

2022-07-19 17:48 UTC, jamshut007 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +
удалил

2022-07-19 18:42 UTC, merged